      var carCompanies = [ { id: 1,
                             name: 'Skyview Taxi',
                             address: '65 East Main Street, Somerville, NJ 08876, USA',
                             costPerMile: 0.65 } ,
                            { id: 2,
                             name: 'American Taxi',
                             address: '87 West Main Street, Somerville, NJ 08876, USA',
                             costPerMile: 0.75 },
                            { id: 3,
                             name: 'Saddle Up Car Service LLC',
                             address: '129 South 10th Avenue, Manville, NJ 08835, USA',
                             costPerMile: 1.35 },
                            { id: 4,
                             name: 'Somerville Taxi',
                             address: 'Division Street, Somerville, NJ 08876, USA',
                             costPerMile: 0.70 },
                            { id: 5,
                             name: 'Empire Car Service' ,
                             address: '1417 Gravesend Neck Road, Brooklyn, NY 11229, USA',
                             costPerMile: 4.00 },
                            { id: 6,
                             name: 'Seagull Transportation',
                             address: '2692 Coney Island Avenue, Brooklyn, NY 11235, USA',
                             costPerMile: 4.00 },
                            { id: 7,
                             name: 'Best Ride',
                             address: '1009 Avenue Z, Brooklyn, NY 11235, USA',
                             costPerMile: 4.50 },
                            { id: 8,
                             name: 'Prestige Car Service',
                             address: '387 Avenue X, Brooklyn, NY 11223, USA' ,
                             costPerMile: 3.50 },
                            { id: 9,
                             name: 'KingsBay',
                             address: '2111 Avenue Z, Brooklyn, NY 11235, USA',
                             costPerMile: 4.50 },
                            { id: 10,
                             name: 'Oceana Car and Limo',
                             address: '2395 Coney Island Avenue, Brooklyn, NY 11223, USA',
                             costPerMile: 5.50 }
                         ] ;

/* values returned by the google
"Statue of Liberty National Monument, New York, NY", 
"65 East Main Street, Somerville, NJ 08876, USA", 
"Division Street, Somerville, NJ 08876, USA", 
"87 West Main Street, Somerville, NJ 08876, USA", 
"129 South 10th Avenue, Manville, NJ 08835, USA", 
"1417 Gravesend Neck Road, Brooklyn, NY 11229, USA", 
"2692 Coney Island Avenue, Brooklyn, NY 11235, USA", 
"1009 Avenue Z, Brooklyn, NY 11235, USA", 
"387 Avenue X, Brooklyn, NY 11223, USA", 
"2111 Avenue Z, Brooklyn, NY 11235, USA", 
"2395 Coney Island Avenue, Brooklyn, NY 11223, USA"
*/
